"""PostgreSQL DDL for the business tables that the application repository layer manages.

These tables mirror the SQLite ``_SCHEMA`` block in ``infra/db.py``. The split
follows the Stage6B Postgres migration design: dedicated JSONB columns replace
``json_extract(data, ...)`` lookups, ``bytea`` keeps the legacy embedding blob
format, and ``BIGINT GENERATED BY DEFAULT AS IDENTITY`` replaces the SQLite
``AUTOINCREMENT`` primary keys.
"""

from __future__ import annotations

KV_TABLE = """
CREATE TABLE IF NOT EXISTS kv (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    expires_at DOUBLE PRECISION
);
"""

COMMIT_HISTORY_TABLE = """
CREATE TABLE IF NOT EXISTS commit_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT NOT NULL,
    platform TEXT NOT NULL,
    file_path TEXT NOT NULL,
    commit_message TEXT NOT NULL,
    commit_time TEXT NOT NULL,
    full_content TEXT NOT NULL
);
"""

SOURCE_DATA_TABLE = """
CREATE TABLE IF NOT EXISTS source_data (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    description TEXT NOT NULL,
    published_date TEXT NOT NULL,
    source TEXT NOT NULL,
    category TEXT NOT NULL,
    author TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    fetched_at TEXT NOT NULL,
    ingestion_date TEXT NOT NULL,
    adapter_name TEXT NOT NULL,
    status TEXT
);
"""

SOURCE_DATA_INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_source_data_source ON source_data(source)",
    "CREATE INDEX IF NOT EXISTS idx_source_data_fetched_at ON source_data(fetched_at)",
    "CREATE INDEX IF NOT EXISTS idx_source_data_status ON source_data(status)",
    "CREATE INDEX IF NOT EXISTS idx_source_data_ingestion_date ON source_data(ingestion_date)",
    "CREATE INDEX IF NOT EXISTS idx_source_data_published_date ON source_data(published_date)",
]

TASK_LOGS_TABLE = """
CREATE TABLE IF NOT EXISTS task_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id TEXT NOT NULL,
    task_name TEXT NOT NULL,
    start_time TEXT,
    end_time TEXT,
    duration INTEGER,
    status TEXT NOT NULL,
    progress DOUBLE PRECISION,
    message TEXT,
    result_count INTEGER
);
"""

ENTITIES_TABLES = [
    "CREATE TABLE IF NOT EXISTS agents (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb)",
    "CREATE TABLE IF NOT EXISTS skills (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb)",
    "CREATE TABLE IF NOT EXISTS workflows (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb)",
    "CREATE TABLE IF NOT EXISTS mcp_configs (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb)",
    "CREATE TABLE IF NOT EXISTS schedules (id TEXT PRIMARY KEY, data JSONB NOT NULL DEFAULT '{}'::jsonb, updated_at TEXT)",
]

SQL_AUDIT_LOG_TABLE = """
CREATE TABLE IF NOT EXISTS sql_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    statement TEXT NOT NULL,
    operation TEXT NOT NULL,
    param_count INTEGER NOT NULL DEFAULT 0,
    suspicious INTEGER NOT NULL DEFAULT 0,
    suspicious_patterns TEXT NOT NULL DEFAULT '',
    recorded_at BIGINT NOT NULL
);
"""

API_KEYS_TABLE = """
CREATE TABLE IF NOT EXISTS api_keys (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    key_hash TEXT NOT NULL,
    prefix TEXT NOT NULL,
    source_fingerprint TEXT NOT NULL,
    verification_token TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    last_used_at TEXT
);
"""

INTEROP_KEYS_TABLE = """
CREATE TABLE IF NOT EXISTS interop_keys (
    key_id TEXT PRIMARY KEY,
    key_hash TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT '',
    created_at BIGINT NOT NULL,
    approved INTEGER NOT NULL DEFAULT 0,
    rate_limit_per_minute INTEGER NOT NULL DEFAULT 60,
    last_used_at BIGINT,
    request_count INTEGER NOT NULL DEFAULT 0
);
"""

EMBEDDINGS_TABLE = """
CREATE TABLE IF NOT EXISTS embeddings (
    id TEXT PRIMARY KEY,
    doc_id TEXT NOT NULL,
    vec BYTEA,
    metadata JSONB
);
"""

MEMORY_CATEGORIES_TABLE = """
CREATE TABLE IF NOT EXISTS memory_categories (
    id TEXT PRIMARY KEY,
    data JSONB NOT NULL DEFAULT '{}'::jsonb
);
"""

AGENT_MEMORIES_TABLE = """
CREATE TABLE IF NOT EXISTS agent_memories (
    id TEXT PRIMARY KEY,
    content TEXT NOT NULL DEFAULT '',
    tags TEXT NOT NULL DEFAULT '',
    data JSONB NOT NULL DEFAULT '{}'::jsonb
);
"""

KB_CATEGORIES_TABLE = """
CREATE TABLE IF NOT EXISTS kb_categories (
    id TEXT PRIMARY KEY,
    data JSONB NOT NULL DEFAULT '{}'::jsonb
);
"""

KB_DOCUMENTS_TABLE = """
CREATE TABLE IF NOT EXISTS kb_documents (
    id TEXT PRIMARY KEY,
    category_id TEXT,
    data JSONB NOT NULL DEFAULT '{}'::jsonb
);
"""

KB_CHUNKS_TABLE = """
CREATE TABLE IF NOT EXISTS kb_chunks (
    id TEXT PRIMARY KEY,
    document_id TEXT,
    content TEXT NOT NULL DEFAULT '',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);
"""

KB_CHUNK_DEDUP_TABLE = """
CREATE TABLE IF NOT EXISTS kb_chunk_dedup (
    content_hash TEXT PRIMARY KEY,
    chunk_id TEXT NOT NULL,
    created_at TEXT NOT NULL
);
"""

CLICK_EVENTS_TABLE = """
CREATE TABLE IF NOT EXISTS click_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    digest_date TEXT NOT NULL,
    item_url TEXT NOT NULL,
    item_source TEXT,
    item_tags TEXT NOT NULL DEFAULT '[]',
    clicked_at TEXT NOT NULL,
    user_agent TEXT,
    referer TEXT
);
"""

DAILY_DIGEST_ARCHIVES_TABLE = """
CREATE TABLE IF NOT EXISTS daily_digest_archives (
    digest_date TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    total_scanned INTEGER NOT NULL DEFAULT 0,
    approval_status TEXT NOT NULL DEFAULT 'published',
    updated_at TEXT NOT NULL
);
"""

ADAPTER_HEALTH_TABLE = """
CREATE TABLE IF NOT EXISTS adapter_health (
    adapter_id TEXT PRIMARY KEY,
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    disabled INTEGER NOT NULL DEFAULT 0,
    last_status TEXT NOT NULL DEFAULT 'unknown',
    last_error TEXT,
    last_run_at TEXT,
    updated_at TEXT NOT NULL
);
"""


ALL_BUSINESS_TABLES = (
    KV_TABLE,
    COMMIT_HISTORY_TABLE,
    SOURCE_DATA_TABLE,
    *SOURCE_DATA_INDEXES,
    TASK_LOGS_TABLE,
    *ENTITIES_TABLES,
    SQL_AUDIT_LOG_TABLE,
    API_KEYS_TABLE,
    INTEROP_KEYS_TABLE,
    EMBEDDINGS_TABLE,
    MEMORY_CATEGORIES_TABLE,
    AGENT_MEMORIES_TABLE,
    KB_CATEGORIES_TABLE,
    KB_DOCUMENTS_TABLE,
    KB_CHUNKS_TABLE,
    KB_CHUNK_DEDUP_TABLE,
    CLICK_EVENTS_TABLE,
    DAILY_DIGEST_ARCHIVES_TABLE,
    ADAPTER_HEALTH_TABLE,
)
"""Sequence of CREATE TABLE / CREATE INDEX statements for Postgres business tables."""
